[tool.poetry]
name = "postgres-lock"
version = "0.1.0"
description = "Use Postgres as a distributed lock broker"
authors = ["Sean Kerr <sean@code-box.org>"]
readme = "README.md"
packages = [{include = "postgres_lock"}]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
